/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.devzone.proyectodevzonejdbc.frontend;

/**
 *
 * @author pablo03
 */
public class MenuPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaPrincipal = new javax.swing.JPanel();
        panelBarraPrincipal = new javax.swing.JPanel();
        lblEleccion = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblElecccionEVT = new javax.swing.JLabel();
        barraLateral = new javax.swing.JPanel();
        btnRegistros = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelRegistros = new javax.swing.JPanel();
        btnRegistro1 = new javax.swing.JButton();
        btnRegistro2 = new javax.swing.JButton();
        btnRegistro3 = new javax.swing.JButton();
        btnInscripciones = new javax.swing.JButton();
        panelReportes = new javax.swing.JPanel();
        btnReportes1 = new javax.swing.JButton();
        btnReportes2 = new javax.swing.JButton();
        btnReportes3 = new javax.swing.JButton();
        panelInscripciones = new javax.swing.JPanel();
        btnInscripcion1 = new javax.swing.JButton();
        btnInscripcion2 = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraPrincipal.setBackground(new java.awt.Color(50, 56, 68));
        panelBarraPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblAdmin.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("Administrador");

        lblElecccionEVT.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblElecccionEVT.setForeground(new java.awt.Color(255, 255, 255));
        lblElecccionEVT.setText("Operacion");

        javax.swing.GroupLayout panelBarraPrincipalLayout = new javax.swing.GroupLayout(panelBarraPrincipal);
        panelBarraPrincipal.setLayout(panelBarraPrincipalLayout);
        panelBarraPrincipalLayout.setHorizontalGroup(
            panelBarraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdmin)
                .addGap(466, 466, 466)
                .addComponent(lblEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblElecccionEVT, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(lblHome)
                .addGap(18, 18, 18))
        );
        panelBarraPrincipalLayout.setVerticalGroup(
            panelBarraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBarraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBarraPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelBarraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHome)
                            .addComponent(lblEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBarraPrincipalLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(panelBarraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdmin)
                                    .addComponent(lblElecccionEVT))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        barraLateral.setBackground(new java.awt.Color(50, 56, 68));
        barraLateral.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        barraLateral.setForeground(new java.awt.Color(0, 0, 0));

        btnRegistros.setBackground(new java.awt.Color(50, 56, 68));
        btnRegistros.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistros.setText("Registro de datos");
        btnRegistros.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        btnRegistros.setFocusable(false);
        btnRegistros.addActionListener(this::btnRegistrosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(50, 56, 68));
        btnReportes.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        btnReportes.setFocusable(false);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        panelRegistros.setBackground(new java.awt.Color(68, 84, 112));
        panelRegistros.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        btnRegistro1.setBackground(new java.awt.Color(99, 119, 134));
        btnRegistro1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro1.setText("Registrar Lineas de Produccion");
        btnRegistro1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnRegistro1.setFocusable(false);
        btnRegistro1.addActionListener(this::btnRegistro1ActionPerformed);

        btnRegistro2.setBackground(new java.awt.Color(99, 119, 134));
        btnRegistro2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnRegistro2.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro2.setText("Registrar Productos");
        btnRegistro2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnRegistro2.setFocusable(false);
        btnRegistro2.addActionListener(this::btnRegistro2ActionPerformed);

        btnRegistro3.setBackground(new java.awt.Color(99, 119, 134));
        btnRegistro3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnRegistro3.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro3.setText("Registrar Clientes");
        btnRegistro3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnRegistro3.setFocusable(false);
        btnRegistro3.addActionListener(this::btnRegistro3ActionPerformed);

        javax.swing.GroupLayout panelRegistrosLayout = new javax.swing.GroupLayout(panelRegistros);
        panelRegistros.setLayout(panelRegistrosLayout);
        panelRegistrosLayout.setHorizontalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistro1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addComponent(btnRegistro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRegistro3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRegistrosLayout.setVerticalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addComponent(btnRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnInscripciones.setBackground(new java.awt.Color(50, 56, 68));
        btnInscripciones.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnInscripciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripciones.setText("Gestion de ventas");
        btnInscripciones.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        btnInscripciones.setFocusable(false);
        btnInscripciones.addActionListener(this::btnInscripcionesActionPerformed);

        panelReportes.setBackground(new java.awt.Color(68, 84, 112));
        panelReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        btnReportes1.setBackground(new java.awt.Color(99, 119, 134));
        btnReportes1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnReportes1.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes1.setText("Ganancias de productos");
        btnReportes1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnReportes1.setFocusable(false);
        btnReportes1.addActionListener(this::btnReportes1ActionPerformed);

        btnReportes2.setBackground(new java.awt.Color(99, 119, 134));
        btnReportes2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnReportes2.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes2.setText("Ventas a Clientes");
        btnReportes2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnReportes2.setFocusable(false);
        btnReportes2.addActionListener(this::btnReportes2ActionPerformed);

        btnReportes3.setBackground(new java.awt.Color(99, 119, 134));
        btnReportes3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnReportes3.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes3.setText("Solicitudes de ventas");
        btnReportes3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnReportes3.setFocusable(false);
        btnReportes3.addActionListener(this::btnReportes3ActionPerformed);

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReportes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInscripciones.setBackground(new java.awt.Color(68, 84, 112));
        panelInscripciones.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        btnInscripcion1.setBackground(new java.awt.Color(99, 119, 134));
        btnInscripcion1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnInscripcion1.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripcion1.setText("Generar venta");
        btnInscripcion1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnInscripcion1.setFocusable(false);
        btnInscripcion1.addActionListener(this::btnInscripcion1ActionPerformed);

        btnInscripcion2.setBackground(new java.awt.Color(99, 119, 134));
        btnInscripcion2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnInscripcion2.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripcion2.setText("Validar Venta");
        btnInscripcion2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btnInscripcion2.setFocusable(false);
        btnInscripcion2.addActionListener(this::btnInscripcion2ActionPerformed);

        javax.swing.GroupLayout panelInscripcionesLayout = new javax.swing.GroupLayout(panelInscripciones);
        panelInscripciones.setLayout(panelInscripcionesLayout);
        panelInscripcionesLayout.setHorizontalGroup(
            panelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInscripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInscripcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInscripcionesLayout.setVerticalGroup(
            panelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInscripcionesLayout.createSequentialGroup()
                .addComponent(btnInscripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addComponent(btnRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        panelContenedor.setBackground(new java.awt.Color(243, 203, 164));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pantallaPrincipalLayout = new javax.swing.GroupLayout(pantallaPrincipal);
        pantallaPrincipal.setLayout(pantallaPrincipalLayout);
        pantallaPrincipalLayout.setHorizontalGroup(
            pantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pantallaPrincipalLayout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantallaPrincipalLayout.setVerticalGroup(
            pantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaPrincipalLayout.createSequentialGroup()
                .addComponent(panelBarraPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pantallaPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        //Reinicia la GUI AL INICIO
//        regresarMenu();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed
        //Lleva a la opcion de generar/insertar datos
//        setIconoGestion();
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        //Boton que lleva a la generacion de reportes
//        setIconoReportes();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro1ActionPerformed
        //Lleva al frame que registra el evento
//        generarRegistros(1);
    }//GEN-LAST:event_btnRegistro1ActionPerformed

    private void btnRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro2ActionPerformed
        //Lleva a l frame que registra a los participantes
//        generarRegistros(2);
    }//GEN-LAST:event_btnRegistro2ActionPerformed

    private void btnRegistro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro3ActionPerformed
        //Lleva al frame que registra la actividad
//        generarRegistros(3);
    }//GEN-LAST:event_btnRegistro3ActionPerformed

    private void btnInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionesActionPerformed
        //Boton que despliega todas las operaciones con inscripciones
//        setIconoInscripciones();
    }//GEN-LAST:event_btnInscripcionesActionPerformed

    private void btnInscripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcion1ActionPerformed
        //Ejecuta el registro de inscripcion
//        generarInscripciones(1);
    }//GEN-LAST:event_btnInscripcion1ActionPerformed

    private void btnInscripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcion2ActionPerformed
        //Ejecuta el registro de pago
//        generarInscripciones(2);
    }//GEN-LAST:event_btnInscripcion2ActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        //Ejecuta la validacion para generar reportes
//        generarReportes(1);
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnReportes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes2ActionPerformed
        //Ejecuta la validacion para generar reporte de actividades
//        generarReportes(2);
    }//GEN-LAST:event_btnReportes2ActionPerformed

    private void btnReportes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes3ActionPerformed
        //Ejecuta la validacion para generar reportes de eventos
//        generarReportes(3);
    }//GEN-LAST:event_btnReportes3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnInscripcion1;
    private javax.swing.JButton btnInscripcion2;
    private javax.swing.JButton btnInscripciones;
    private javax.swing.JButton btnRegistro1;
    private javax.swing.JButton btnRegistro2;
    private javax.swing.JButton btnRegistro3;
    private javax.swing.JButton btnRegistros;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton btnReportes2;
    private javax.swing.JButton btnReportes3;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblElecccionEVT;
    private javax.swing.JLabel lblEleccion;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JPanel panelBarraPrincipal;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelInscripciones;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel pantallaPrincipal;
    // End of variables declaration//GEN-END:variables
}
